### ISSUE TITLE
unable to pull the image "docker.io/kubernetes/redis-slave:v2

### ISSUE THREAD

**Issue by praseed656** [IBM/guestbook#65]
Unable to download this image.

Tried directly pulling using docker pull image but getting the below error:

docker pull redis-slave:v2
Error response from daemon: pull access denied for redis-slave, repository does not exist or may require 'docker login'

**Comment by lfbrieva** [comment]
Events:
  Type     Reason     Age                From                    Message
  ----     ------     ----               ----                    -------
  Normal   Scheduled  21m                default-scheduler       Successfully assigned default/redis-slave-5db5dcfdfd-t8drf to 10.76.202.104
  Normal   Pulling    20m (x4 over 21m)  kubelet, 10.76.202.104  pulling image "kubernetes/redis-slave:v2"
  Warning  Failed     20m (x4 over 21m)  kubelet, 10.76.202.104  Failed to pull image "kubernetes/redis-slave:v2": rpc error: code = Unknown desc = failed to resolve image "docker.io/kubernetes/redis-slave:v2": server message: insufficient_scope: authorization failed
  Warning  Failed     20m (x4 over 21m)  kubelet, 10.76.202.104  Error: ErrImagePull
  Normal   BackOff    6m (x63 over 21m)  kubelet, 10.76.202.104  Back-off pulling image "kubernetes/redis-slave:v2"
  Warning  Failed     1m (x84 over 21m)  kubelet, 10.76.202.104  Error: ImagePullBackOff

**Comment by daherbie** [comment]
https://hub.docker.com/r/kubernetes/redis-slave/   gives a 404 now.

**Comment by chaitanyavutukuru** [comment]
Faced same issue today.

**Comment by chaitanyavutukuru** [comment]
Faced same issue today.

**Comment by KeenH** [comment]
I even cannot find the image:  kubernetes/redis-slave:v2.   and I encounter the same issue today.

**Comment by rvennam** [comment]
fixed with #67
